import type { NextPage } from 'next';
import Head from 'next/head';
import { RecoilRoot } from 'recoil';
import { Suspense } from 'react';

import DataLoader from '../components/DataLoader';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <RecoilRoot>
          {/* <TodoList /> */}
          <Suspense fallback={<div>Loading...</div>}>
            <DataLoader />
          </Suspense>
        </RecoilRoot>
      </main>
    </div>
  );
};

export default Home;
